protected/models/Trandetail.php
<?php

/**
 * This is the model class for table "trandetail".
 *
 * The followings are the available columns in table 'trandetail':
 * @property integer $trandetail_id
 * @property integer $id_inventory
 * @property string $kode_barang
 * @property string $nama_barang
 * @property string $type
 * @property double $quantity
 * @property string $satuan
 * @property integer $tranheader_id
 * @property string $jenis_dokumen
 * @property string $dp_nomor
 * @property string $dp_tanggal
 * @property string $bpb_nomor
 * @property string $bpb_tanggal
 * @property string $keterangan
 *
 * The followings are the available model relations:
 * @property Tranheader $tranheader
 */
class Trandetail extends CActiveRecord
{
	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return Trandetail the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'trandetail';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('id_inventory, kode_barang, nama_barang, type, quantity, satuan, tranheader_id', 'required'),
			array('id_inventory, tranheader_id', 'numerical', 'integerOnly'=>true),
                        array('quantity', 'numerical'),
			array('kode_barang, type, jenis_dokumen, dp_nomor, bpb_nomor', 'length', 'max'=>30),
			array('satuan', 'length', 'max'=>20),
			array('dp_tanggal, bpb_tanggal, keterangan', 'safe'),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('trandetail_id, id_inventory, kode_barang, nama_barang, type, quantity, satuan, tranheader_id, jenis_dokumen, dp_nomor, dp_tanggal, bpb_nomor, bpb_tanggal, keterangan', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'tranheader' => array(self::BELONGS_TO, 'Tranheader', 'tranheader_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'trandetail_id' => 'Trandetail',
			'id_inventory' => 'Id Inventory',
			'kode_barang' => 'Kode Barang',
			'nama_barang' => 'Nama Barang',
			'type' => 'Type',
			'quantity' => 'Quantity',
			'satuan' => 'Satuan',
			'tranheader_id' => 'Tranheader',
			'jenis_dokumen' => 'Jenis Dokumen',
			'dp_nomor' => 'DP Nomor',
			'dp_tanggal' => 'DP Tanggal',
			'bpb_nomor' => 'BPB Nomor',
			'bpb_tanggal' => 'BPB Tanggal',
			'keterangan' => 'Keterangan',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('trandetail_id',$this->trandetail_id);
		$criteria->compare('id_inventory',$this->id_inventory);
		$criteria->compare('kode_barang',$this->kode_barang,true);
		$criteria->compare('nama_barang',$this->nama_barang,true);
		$criteria->compare('type',$this->type,true);
		$criteria->compare('quantity',$this->quantity);
		$criteria->compare('satuan',$this->satuan,true);
		$criteria->compare('tranheader_id',$this->tranheader_id);
		$criteria->compare('jenis_dokumen',$this->jenis_dokumen,true);
		$criteria->compare('dp_nomor',$this->dp_nomor,true);
		$criteria->compare('dp_tanggal',$this->dp_tanggal,true);
		$criteria->compare('bpb_nomor',$this->bpb_nomor,true);
		$criteria->compare('bpb_tanggal',$this->bpb_tanggal,true);
		$criteria->compare('keterangan',$this->keterangan,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}
        
        public function search2($id)
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;
                $criteria->condition='tranheader_id='.$id;

		$criteria->compare('trandetail_id',$this->trandetail_id);
		$criteria->compare('id_inventory',$this->id_inventory);
		$criteria->compare('kode_barang',$this->kode_barang,true);
		$criteria->compare('nama_barang',$this->nama_barang,true);
		$criteria->compare('type',$this->type,true);
		$criteria->compare('quantity',$this->quantity);
		$criteria->compare('satuan',$this->satuan,true);
		$criteria->compare('tranheader_id',$this->tranheader_id);
		$criteria->compare('jenis_dokumen',$this->jenis_dokumen,true);
		$criteria->compare('dp_nomor',$this->dp_nomor,true);
		$criteria->compare('dp_tanggal',$this->dp_tanggal,true);
		$criteria->compare('bpb_nomor',$this->bpb_nomor,true);
		$criteria->compare('bpb_tanggal',$this->bpb_tanggal,true);
		$criteria->compare('keterangan',$this->keterangan,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}
        
        public function behaviors() {
        return array(
            'ERememberFiltersBehavior' => array(
                'class' => 'application.components.ERememberFiltersBehavior',
                'defaults' => array(), // optional line 
                'defaultStickOnClear' => false   //optional line 
            ),
        );
    }

}

protected/controllers/TrandetailController.php
<?php

class TrandetailController extends Controller {

    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout = '//layouts/column2';

    /**
     * @return array action filters
     */
    public function filters() {
        return array(
            'accessControl', // perform access control for CRUD operations
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules() {
        return array(
            array('allow', // allow all users to perform 'index' and 'view' actions
                'actions' => array('index', 'view'),
                'users' => array('*'),
            ),
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions' => array(''),
                'users' => array('@'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions' => array('admin', 'delete', 'transactionAdd', 'create', 'update'),
                //'users'=>array('admin'),
                'expression' => '$user->getRole()<=1',
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id) {
        $this->render('view', array(
            'model' => $this->loadModel($id),
        ));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate($id) {
        /*if (!isset(Yii::app()->session["lastTransaksi"])) {
            Yii::app()->session["lastTransaksi"] = array();
        }

        if (empty($_GET)) {
            $_GET = Yii::app()->session["lastTransaksi"];
        } else {
            Yii::app()->session["lastTransaksi"] = $_GET;
           // $Trandetail_page=Yii::app()->session["lastTransaksi"];
        }*/
        
        $model = new Trandetail;

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['Trandetail'])) {
            $model->attributes = $_POST['Trandetail'];
            //$str=str_replace(",",".",$model->quantity);
            //$model->quantity=$str;
            $model->tranheader_id = $id;
            //$model->satuan = 'PCS';
            if ($model->save())
                $this->redirect(array('transactionAdd', 'id' => $id, 'Trandetail_page'=>99999999));
        }

        $this->render('create', array(
            'model' => $model,
            'id' => $id,
        ));
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id, $idTranHeader) {
        /*if (!isset(Yii::app()->session["lastTransaksi"])) {
            Yii::app()->session["lastTransaksi"] = array();
        }

        if (empty($_GET)) {
            $_GET = Yii::app()->session["lastTransaksi"];
        } else {
            Yii::app()->session["lastTransaksi"] = $_GET;
           // $Trandetail_page=Yii::app()->session["lastTransaksi"];
        }*/
        $model = $this->loadModel($id);

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['Trandetail'])) {
            $model->attributes = $_POST['Trandetail'];
            //$model->tran
            if ($model->save())
                $this->redirect(array('transactionAdd', 'id' => $idTranHeader));
        }

        $this->render('update', array(
            'model' => $model,
            'id' => $idTranHeader,
        ));
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($id) {
        if (Yii::app()->request->isPostRequest) {
            // we only allow deletion via POST request
            $model = $this->loadModel($id);
            $this->loadModel($id)->delete();

            // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
            if (!isset($_GET['ajax'])) {
                //$this->redirect(array('transactionAdd','id'=>$this->loadModel($id)->tranheader_id));
                $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('transactionAdd', 'id' => $model->tranheader_id));
            }
        } else
            throw new CHttpException(400, 'Invalid request. Please do not repeat this request again.');
    }

    /**
     * Lists all models.
     */
    public function actionIndex() {
        $dataProvider = new CActiveDataProvider('Trandetail');
        $this->render('index', array(
            'dataProvider' => $dataProvider,
        ));
    }

    /**
     * Manages all models.
     */
    public function actionAdmin($id) {
       /*if (!isset(Yii::app()->session["lastTransaksi"])) {
            Yii::app()->session["lastTransaksi"] = array();
        }

        if (empty($_GET)) {
            $_GET = Yii::app()->session["lastTransaksi"];
        } else {
            Yii::app()->session["lastTransaksi"] = $_GET;
        }*/
        
        $model = new Trandetail('search');
        $model->unsetAttributes();  // clear any default values
        //$model = new CActiveDataProvider('Trandetail', array(
        //    'criteria' => array(
          //      'condition' => 'tranheader_id=' . $id,
            //),
            //'pagination' => array(
            //    'pageSize' => 10,
            //),
       // ));
        
        if (isset($_GET['Trandetail']))
            $model->attributes = $_GET['Trandetail'];

        $this->render('admin', array(
            'model' => $model,
        ));
    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer the ID of the model to be loaded
     */
    public function loadModel($id) {
        $model = Trandetail::model()->findByPk($id);
        if ($model === null)
            throw new CHttpException(404, 'The requested page does not exist.');
        return $model;
    }

    /**
     * Performs the AJAX validation.
     * @param CModel the model to be validated
     */
    protected function performAjaxValidation($model) {
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'trandetail-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }

    public function actionTransactionAdd($id) {
        if (!isset(Yii::app()->session["lastTransaksi"])) {
            Yii::app()->session["lastTransaksi"] = array();
        }

        if (empty($_GET)) {
            $_GET = Yii::app()->session["lastTransaksi"];
        } else {
            Yii::app()->session["lastTransaksi"] = $_GET;
           // $Trandetail_page=Yii::app()->session["lastTransaksi"];
        }
        //$id=95;
        //$trandetail = new Trandetail('search');
        //$trandetail->unsetAttributes();  // clear any default values
        
        $tranheader = Tranheader::model()->findByAttributes(array('tranheader_id' => $id));
        /*$trandetail = new CActiveDataProvider('Trandetail', array(
            'criteria' => array(
                'condition' => 'tranheader_id=' . $id,
            ),
            'pagination' => array(
                'pageSize' => 10,
            ),
        ));*/   //$trandetail->unsetAttributes(); 
        //$trandetail = new Trandetail("search2('.$id.')");
        $trandetail = new Trandetail("search");
        $trandetail->unsetAttributes(); 

        $this->render('transactionAdd', array(
            'tranheader' => $tranheader,
            'trandetail' => $trandetail,
            //'Trandetail_page'=>$Trandetail_page,
        ));
    }

}

protected/views/trandetail/_form.php
<script type="text/javascript">

    /*function samain(idElement, idElement2, idElement3, hidden)
     {
     var element = document.getElementById(idElement);
     var val = element.selectedIndex;
     document.getElementById(idElement2).selectedIndex = val;
     document.getElementById(idElement3).selectedIndex = val;
     //document.getElementById(hidden).value=document.getElementById(idElement3).value;
     }*/

    function enable()
    {
        document.getElementById("Trandetail_satuan").disabled = false;
        document.getElementById("Trandetail_type").disabled = false;
        document.getElementById("Trandetail_id_inventory").disabled = false;

        //document.getElementById("status").disabled=false;

    }

    function fillAtributBarang()
    {
        var index = document.getElementById("Trandetail_nama_barang").selectedIndex;
        var satuan = document.getElementById("Trandetail_nama_barang").options[index].getAttribute('satuan');
        var id_inv = document.getElementById("Trandetail_nama_barang").options[index].getAttribute('id_inv');
        var type = document.getElementById("Trandetail_nama_barang").options[index].getAttribute('tipe');

        document.getElementById("Trandetail_satuan").value = satuan;
        document.getElementById("Trandetail_type").value = type;
        document.getElementById("Trandetail_id_inventory").value = id_inv;

    }

    function nullAtributBarang()
    {
        document.getElementById("Trandetail_satuan").value = "";
        document.getElementById("Trandetail_type").value = "";
        document.getElementById("Trandetail_id_inventory").value = "";

    }

</script>
<?php
///echo $idheader;
//if(isset($_GET['idheader'])){ //get id header untuk create
$header = Tranheader::model()->findByPk($idheader);
//echo $header->type_tran;
//}
?>

<?php
$form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
    'id' => 'trandetail-form',
    'enableAjaxValidation' => false,
    'htmlOptions' => array('onsubmit' => 'enable()'),
        ));
?>

<p class="help-block">Fields with <span class="required">*</span> are required.</p>

<?php echo $form->errorSummary($model); ?>

<?php if ($header->type_tran == 'P') { ?>
    <div class="row">
        <div class="span9">
            <?php echo $form->textFieldRow($model, 'jenis_dokumen', array('class' => 'span7')); ?>
        </div>
        <div class="span4">
            <?php echo $form->textFieldRow($model, 'dp_nomor', array('class' => 'span3')); ?>
            <?php echo $form->textFieldRow($model, 'bpb_nomor', array('class' => 'span3')); ?>
        </div>

        <div class="span4">
            <label for="Trandetail_dp_tanggal">DP Tanggal</label>
            <input class="span3" type="date" id="Trandetail_dp_tanggal" name="Trandetail[dp_tanggal]" value="<?php //echo $date1;   ?>" />

            <label for="Trandetail_bpb_tanggal">BPB Tanggal</label>
            <input class="span3" type="date" id="Trandetail_bpb_tanggal" name="Trandetail[bpb_tanggal]" value="<?php //echo $date1;   ?>" />

        </div></div>
<?php } ?>

<label for="Trandetail_kode_barang" class="required">Kode Barang <span class="required">*</span></label>
<?php
echo $form->dropDownList($model, 'kode_barang', CHtml::listData(Inventorymaster::model()->findAll(
//array(
//'select'=>'*',
//'condition'=>"code NOT IN(SELECT kode_barang FROM trandetail WHERE tranheader_id ='$idheader'))")
                ), 'code', 'code'), array(
    'onChange' => 'nullAtributBarang()',
    'prompt' => '-- Pilih Kode Barang --',
    'ajax' => array(
        'type' => 'POST',
        'url' => Yii::app()->createUrl('//InventoryMaster/LoadBarang'), //or $this->createUrl('loadcities') if '$this' extends CController
        'update' => '#Trandetail_nama_barang', //or 'success' => 'function(data){...handle the data in the way you want...}',
        'data' => array('Trandetail_kode_barang' => 'js:this.value', 'YII_CSRF_TOKEN' => Yii::app()->request->csrfToken),
)));
?>


<label for="Trandetail_nama_barang" class="required">Nama Barang <span class="required">*</span></label>
<select class="span7" onchange="fillAtributBarang()" name="Trandetail[nama_barang]" id="Trandetail_nama_barang" class="">
    <?php
    $data = new CActiveDataProvider('Inventorymaster', array(
        'criteria' => array(
            'condition' => "code='$model->kode_barang'",
        //'with'=>array('idMasukHeader'=>array('joinType'=>'LEFT JOIN')),
        //'order'=>'vehicle_id DESC',
        )
    ));
    echo "<option value='' id_inv='' satuan='' tipe=''>-- Pilih Barang --</option>";
    foreach ($data->getData() as $i => $ii) {
        //foreach ($data2 as $value2=>$id_inventory){
        //echo CHtml::tag('option', array('value'=>$ii['description'], 'id_inv'=>$ii['id_inventory'], 'satuan'=>$ii['satuan'], 'tipe'=>$ii['type']),CHtml::encode($ii['description']),true);
        ?><option <?php if ($model->id_inventory == $ii['id_inventory']) echo "selected=selected"; ?> value="<?php echo $ii['description']; ?>" id_inv="<?php echo $ii['id_inventory']; ?>" satuan="<?php echo $ii['satuan']; ?>" tipe="<?php echo $ii['type']; ?>"><?php echo $ii['description']; ?></option>
        <?php
        //  }
    }
    ?>
</select>

<div class="row">
    <div class="span2">
<?php echo $form->textFieldRow($model, 'type', array('disabled' => 'disabled', 'class' => 'span2')); ?>
    </div>
    <div class="span3">
<?php echo $form->textFieldRow($model, 'quantity', array('class' => 'span3')); ?>
    </div>
        <div class="span2">
<?php echo $form->textFieldRow($model, 'satuan', array('disabled' => 'disabled', 'class' => 'span2')); ?>
        </div>
</div>
<?php echo $form->hiddenField($model, 'id_inventory'); ?>


<?php if ($header->type_tran == 'P') { ?>
    <?php echo $form->textAreaRow($model, 'keterangan', array('class' => 'span7')); ?>
<?php } ?>



<div class="form-actions">
    <?php
    $this->widget('bootstrap.widgets.TbButton', array(
        'buttonType' => 'submit',
        'type' => 'primary',
        'label' => $model->isNewRecord ? 'ADD' : 'Save',
    ));
    ?>
</div>

<?php $this->endWidget(); ?>



protected/views/trandetail/create.php
<?php
$this->breadcrumbs=array(
	'Trandetails'=>array('index'),
	'Create',
);

$this->menu=array(
	//array('label'=>'List Trandetail','url'=>array('index')),
	//array('label'=>'Manage Trandetail','url'=>array('admin')),
);
?>

<h1>Create Trandetail</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model, 'idheader'=>$id)); ?>

protected/views/trandetail/transactionAdd.php
<script>

</script>
<style>
    .transaksi{
        height: 20px;
        width: 100%;
    }
</style>
<?php 
    Yii::app()->clientScript->registerCssFile(Yii::app()->baseUrl.'/js/bootstrap/css/bootstrap.min.css');    
    Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl.'/js/bootstrap/js/bootstrap.min.js'); 
?>
<?php
$this->breadcrumbs = array(
    'Daftar Transaksi/',
    'Transaksi/',
    $tranheader->tranheader_id,
);

$this->menu = array(
//array('label'=>'List Tranheader','url'=>array('index')),
    array('label' => 'Transaksi Baru', 'url' => array('//tranheader/createNewTransaction')),
        //array('label'=>'Update Transaksi', 'url'=>array('')),
);
?>
<?php
if (!isset(Yii::app()->session["lastTransaksi"])) {
            Yii::app()->session["lastTransaksi"] = array();
        }

        if (empty($_GET)) {
            $_GET = Yii::app()->session["lastTransaksi"];
        } else {
            Yii::app()->session["lastTransaksi"] = $_GET;
           // $Trandetail_page=Yii::app()->session["lastTransaksi"];
        }
        
        echo Yii::app()->session["Trandetail_page"];
?>

<h1>Transaksi <?php //echo $tranheader->tranheader_id;     ?></h1>
<?php /*
$this->widget('ext.editable.EditableField', array(
    'type'      => 'text',
    'model'     => $tranheader,
    'attribute' => 'type_tran',
    'url'       => $this->createUrl('trandetail/update'),  //url for submit data
));*/ 
?>
<?php
//function($tranheader){
if ($tranheader->type_tran == 'P') {
    $tipe = 'Pemasukan';
} else if ($tranheader->type_tran == 'K') {
    $tipe = 'Pengeluaran';
//$class=$data->status_tran;
} else if ($tranheader->type_tran == 'S') {
    $tipe = 'Penyesuaian';
} else if ($tranheader->type_tran == 'O') {
    $tipe = 'Stok Opname';
} else if ($tranheader->type_tran == 'A') {
    $tipe = 'Saldo Awal';
}

if ($tranheader->status_tran == 'P') {
    $status = 'Processed';
} else {
    $status = 'New';
}
?>
<?php
$this->widget('bootstrap.widgets.TbDetailView', array(
    'data' => $tranheader,
    'attributes' => array(
        'tranheader_id',
        array(
            'name' => 'tanggal_tran',
            // 'type'=>'raw',
            'value' => Yii::app()->dateFormatter->format("d MMMM y", strtotime($tranheader->tanggal_tran)),
        ),
        array(
            'name' => 'type_tran',
            'value' => $tipe,
        ),
        array(
            'name' => 'status_tran',
            'value' => $status,
        ),
        //'user_id',
        'keterangan',
        'user.user_name',
    ),
));
?>

<div class="transaksi" >

    <?php
    //$dummy = new EKeepSelection('#transaksi-detail'); 
    
    if ($tranheader->type_tran == 'P') {
        $visible = true; //jika tipe A, kolom visible
        $hapus = CHtml::link("Hapus", "#", array("style" => 'pointer-events: none; color:gray;'));
    } else {
        $visible = false;
    }

    if ($tranheader->status_tran == 'P') {
        $processed = false;
    } else {
        $processed = true;
    }
    
    


    $this->widget('bootstrap.widgets.TbGridView', array(
        'id' => 'transaksi-detail',
        'dataProvider' => $trandetail->search2($tranheader->tranheader_id),
        //'filter'=>$trandetail,
        'columns' => array(
             //array('class'=>'CCheckBoxColumn'), 
            
            array(
                'name'=>'trandetail_id',
                'header' => 'No.',
                'value' => '$this->grid->dataProvider->pagination->currentPage * $this->grid->dataProvider->pagination->pageSize + ($row+1)
',
            ),
            array(
                'name' => 'jenis_dokumen',
                'value' => '$data->jenis_dokumen',
                'visible' => $visible,
            ),
            array(
                'name' => 'dp_nomor',
                'value' => '$data->dp_nomor',
                'visible' => $visible,
            ),
            array(
                'name' => 'dp_tanggal',
                'value' => '$data->dp_tanggal',
                'visible' => $visible,
            ),
            array(
                'name' => 'bpb_nomor',
                'value' => '$data->bpb_nomor',
                'visible' => $visible,
            ),
            array(
                'name' => 'bpb_tanggal',
                'value' => '$data->bpb_tanggal',
                'visible' => $visible,
            ),
            'kode_barang',
            'nama_barang',
            //'quantity',
            array(
                    'name'=>'quantity',
                    'value'=>'number_format($data->quantity,4,",",".")',
                    'htmlOptions'=>array('style'=>'text-align:right;'),
                    ),
            'satuan',
            //'tranheader_id',
            array(
                'name' => 'keterangan',
                'value' => '$data->keterangan',
                'visible' => $visible,
            ),
            array(
                'name' => 'Edit',
                'header' => 'Edit',
                'type' => 'raw',
                'htmlOptions' => array('width' => '40'),
                'value' => 'CHtml::link("Edit", Yii::app()->createUrl("/trandetail/update", array("idTranHeader" => $data["tranheader_id"], "id" => $data["trandetail_id"])))',
                'visible' => $processed,
            ),
            array(
                'name' => 'Hapus',
                'header' => 'Hapus',
                'type' => 'raw',
                //'value'=>'CHtml::link("Delete",Yii::app()->createUrl("/trandetail/delete"),array("submit"=>array("delete", "id"=>$data["trandetail_id"]), "confirm" => "Are you sure?")))',
                'value' => 'CHtml::link("Hapus","#", array("submit"=>array("delete", "id"=>$data["trandetail_id"]), "confirm" => "Are yous sure?"))',
                'htmlOptions' => array('width' => '40'),
                'visible' => $processed,
            ),
           
        /* array(
          'class'=>'bootstrap.widgets.TbButtonColumn',
          ), */
        ),
    ));
    //}
    ?>


<?php
if ($tranheader->status_tran == 'N') {//if N
    echo CHtml::button('+ADD', array(
        'submit' => array('trandetail/create', 'id' => $tranheader->tranheader_id),
            //'confirm' => 'Are you sure?'
            // or you can use 'params'=>array('id'=>$id)
            // 'disabled'=>'disabled',
            'class'=>'btn btn-primary',
            )
    );
    ?>

        <?php
        echo CHtml::button('PROCESS', array(
            'submit' => array('//tranheader/process', 'id' => $tranheader->tranheader_id),
                //'confirm' => 'Are you sure?'
                // or you can use 'params'=>array('id'=>$id)
            'class'=>'btn btn-success',
                )
        );
    }//endif
    ?>
    <br/>
    <br/>
    <br/>
</div>


<!--<a class="delete" title="" rel="tooltip" href="/ogawa/index.php/trandetail/delete/86" data-original-title="Delete"><i class="icon-trash"></i></a>-->

<?php
//echo CHtml::linkButton('+ADD',array('trandetail/create',
//                                 'id'=>$tranheader->tranheader_id)); 
?>

<?php
//echo CHtml::link('PROCESS',array('//tranheader/process',
//                                 'id'=>$tranheader->tranheader_id)); 
?>

<?php
//$results = Tranheader::model()->findByAttributes(array('status_tran'=>'N'));
//$count = count ( $results );
//echo $count;
?>